### ISSUE TITLE
Bug - beams

### ISSUE THREAD

**Issue by luxi-liu97** [matthewcpp/ABCUnity#3]
Hi Matthew! I've been using your package and it's been very helpful for my use case. I've noticed however that there is some issue with beaming?
E.g. for this string:
`X:1 
 M:4/4 
 L:1/4 

b/4a/4^g/2 a/4b/4a/2 ^g/2^fz1/2 |`

I would appreciate if the first three notes (b/4a/4^g/2) and the second three notes (a/4b/4a/2) were beamed together correctly. I've attached a picture with how it currently renders.
Thanks so much!
<img width="471" alt="Screenshot 2024-06-04 at 23 30 08" src="https://github.com/matthewcpp/ABCUnity/assets/75979110/5f2e4328-f675-42ae-aef5-3f7ea11acc0f">

**Comment by matthewcpp** [comment]
Hi there,  Thanks for the message, I had a look at the code which deals with the beams and see the issues that are causing the behavior that you are experiencing.  There are changes needed on both the parsing and rendering side.  That being said, realistically, i wont be able try implementing a fix before the end of the week or weekend.

**Comment by luxi-liu97** [comment]
Ok, no rush. Thanks Matthew.

**Comment by matthewcpp** [comment]
Hi there, I just merged some code into master which should solve your issue.  After the fix your sample code now renders like this:
![image](https://github.com/matthewcpp/ABCUnity/assets/2367648/226cc9a9-082a-4494-99f5-1848233c1c74)
Hopefully this solves your issue!
